---
- name: Reboot hosts
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for host to come back
  local_action:
    module: wait_for
      host={{ ansible_host }}
      port=22
      delay=1
      timeout=300
  become: false
